# Generated by Django 3.2.9 on 2021-11-29 12:53

from django.db import migrations, models
import store.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=14, verbose_name='Жанр')),
                ('slug', models.SlugField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('poster', models.ImageField(upload_to=store.utils.get_path, verbose_name='Постер')),
                ('banner', models.ImageField(upload_to=store.utils.get_path, verbose_name='Баннер')),
                ('describe', models.TextField(max_length=300)),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(related_name='genre', related_query_name='genres', to='store.Genres')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'db_table': 'games',
            },
        ),
    ]
